name: Build main.asm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NASM
        shell: pwsh
        run:
          Invoke-WebRequest -Uri "https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win64/nasm-2.15.05-win64.zip" -Outfile "nasm.zip";
          Expand-Archive -Path "nasm.zip" -DestinationPath "./";
          pwd;
      - name: Test nasm
        run: nasm --version
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
      - name: Build
        run:
          cd %USERPROFILE%\AppData\Local\bin\NASM
          nasm main.asm -f win32
          g++ main.obj -O
          echo Success!
