name: Build main.asm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NASM with Chocolatey
        uses: crazy-max/ghaction-chocolatey@v1.4.1
        with:
          args: install nasm
      - name: Test nasm
        with:
          run: nasm --version
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
      - name: Build
        run:
          cd %USERPROFILE%\AppData\Local\bin\NASM
          nasm main.asm -f win32
          g++ main.obj -O
          echo Success!
